# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.7
  # run mypy checks over app, pulse, pressure separately
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.710
    hooks:
      - id: mypy
        name: mypy (app)
        exclude: "^(pulse|pressure)/"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.710
    hooks:
      - id: mypy
        name: mypy (app)
        exclude: "^(app|pulse|pressure)/"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.710
    hooks:
      - id: mypy
        name: mypy (pulse)
        files: "^pulse/"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.710
    hooks:
      - id: mypy
        name: mypy (pressure)
        files: "^pressure/"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
        # don't check formatting for helm charts
        exclude: "^_infra/"
      - id: check-json
        # vscode files contain JSON w/ comments
        exclude: "^.vscode/"
      - id: check-added-large-files
