version: "3.2"

services:
  web:
    container_name: payment.web
    build:
      context: "."
      args:
        - FURY_TOKEN=${FURY_TOKEN:?FURY_TOKEN. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_USERNAME=${ARTIFACTORY_USERNAME:?ARTIFACTORY_USERNAME. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD:?ARTIFACTORY_PASSWORD. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
    volumes:
      - $PWD/app:/home/app
      - $PWD/development:/home/development
      - $PWD/_infra/web/gunicorn_conf_local.py:/home/_infra/web/gunicorn_conf_local.py
    ports:
      - ${WEB_PORT:?Please specify WEB_PORT}:${WEB_PORT}
    environment:
      - DSJ_DB_ENDPOINT=payment.dsj-postgres
    command: "./development/start-local-server.sh -e local -p ${WEB_PORT}"
    tty: true
    depends_on:
      - payment.dsj-postgres
      - payment.redis
      - payment.stripe-mock
      - payment.redis-cluster

  cron:
    container_name: payin.cron
    build:
      context: "."
      args:
        - FURY_TOKEN=${FURY_TOKEN:?FURY_TOKEN. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_USERNAME=${ARTIFACTORY_USERNAME:?ARTIFACTORY_USERNAME. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD:?ARTIFACTORY_PASSWORD. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
    volumes:
      - $PWD/app:/home/app
      - $PWD/development:/home/development
    command: ["python", "app/payin_cron.py"]
    tty: true
    depends_on:
      - payment.dsj-postgres
      - payment.redis
      - payment.stripe-mock
      - payment.redis-cluster

  payout-cron:
    container_name: payout.cron
    build:
      context: "."
      args:
        - FURY_TOKEN=${FURY_TOKEN:?FURY_TOKEN. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_USERNAME=${ARTIFACTORY_USERNAME:?ARTIFACTORY_USERNAME. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD:?ARTIFACTORY_PASSWORD. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
    volumes:
      - $PWD/app:/home/app
      - $PWD/development:/home/development
    command: ["python", "app/payout_cron.py"]
    tty: true
    depends_on:
      - payment.dsj-postgres
      - payment.redis
      - payment.stripe-mock
      - payment.redis-cluster

  admin:
    container_name: payment.admin
    build:
      context: "."
      args:
        - FURY_TOKEN=${FURY_TOKEN:?FURY_TOKEN. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_USERNAME=${ARTIFACTORY_USERNAME:?ARTIFACTORY_USERNAME. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD:?ARTIFACTORY_PASSWORD. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
    volumes:
      - $PWD/app:/home/app
      - $PWD/development:/home/development
    environment:
      - DSJ_DB_ENDPOINT=payment.dsj-postgres
    command: ["tail", "-f", "/dev/null"]
    tty: true
    depends_on:
      - payment.dsj-postgres
      - payment.redis
      - payment.stripe-mock
      - payment.redis-cluster
