version: "3"
services:
  web:
    build:
      context: "."
      args:
        - FURY_TOKEN=${FURY_TOKEN:?FURY_TOKEN. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_USERNAME=${ARTIFACTORY_USERNAME:?ARTIFACTORY_USERNAME. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
        - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD:?ARTIFACTORY_PASSWORD. Please run New Engineer Setup Guide. https://drd.sh/PZKD9P/}
    volumes:
      - $PWD/app:/home/app
    ports:
      - "8000:80"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    tty: true
