version: '3'
services:
  web:
    build:
      context: '.'
      args:
        - ARTIFACTORY_USERNAME
        - ARTIFACTORY_PASSWORD
        - FURY_TOKEN
    environment:
      ENVIRONMENT: local
      FLASK_APP: "application.main:create_app()"
      FLASK_DEBUG: 1
    volumes:
      - $PWD/application:/home/app/application
      - ${RUNTIME_PATH:-./local-runtime}/data:/srv/runtime/current/data
    ports:
      - "5000:80"
    ##
    # uWSGI: Run as it would in production
    # python: Run with auto-reload (faster development)
    ##
    # command: "uwsgi --ini /etc/uwsgi/uwsgi_compose.ini"
    command: "python3 -m flask run -h 0.0.0.0 -p 80"
    