apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-conf
data:
  nginx.conf: |
    daemon     off;
    error_log  /dev/stderr warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      include       /etc/nginx/conf.d/*.conf;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $upstream_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        '$request_time $upstream_response_time $pipe';

      access_log  /dev/stdout main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-flask-app-conf
data:
  flask-app.conf: |
    server {
      location / {
        try_files $uri @app;
      }

      location @app {
        include uwsgi_params;
        uwsgi_pass unix:/var/run/flask-app.sock;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-environment
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: !!str {{ $value }}
  {{- end -}}
